export const FOOTER = [
  "About",
  "Help Center",
  "Terms of Policy",
  "Privacy Policy",
  "Cookies Policy",
  "Ads info",
  "Blog",
  "Status",
  "Carrier",
  "Brand Resources",
  "Advertsing",
  "Marketing",
  "Twitter For Business",
  "Developers",
  "Directory",
  "Setting",
  "© 2024 Twitter, Inc.",
];
